import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {

  const [selectValue, setSelectValue] = useState("")
  const [formValues, setFormValues] = useState(
    { wasteReduction: false, foodSharing: true, tooGoodToGo: true, wasteReductionInput: '', sector: 'gastro' }
  );
  const [result, setResult] = useState(null)


  const handleFormChange = (e) => {
    let name = e.target.name;
    let type = e.target.type;



    var value = null;

    if (type === 'text') {
      if (formValues?.wasteReduction === true) {
        value = e.target.value;
      } else {
        value = "";
      }
    }

    if (type === 'select-one') {
      value = e.target.value;
      formValues.sector = value;
    }

    if (type === 'checkbox') {
      value = e.target.checked;
      if (value === false && formValues?.wasteReductionInput !== "") {
        formValues.wasteReductionInput = "";
      }
    }

    setFormValues({
      ...formValues,
      [name]: value
    })
  }

  const submitForm = async () => {
    let resp = await fetch("api/v1/form", {
      method: 'POST', // *GET, POST, PUT, DELETE, etc.
      mode: 'cors', // no-cors, *cors, same-origin
      cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
      credentials: 'same-origin', // include, *same-origin, omit
      headers: {
        'Content-Type': 'application/json'
        // 'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: JSON.stringify({ "sector": selectValue, ...formValues }) // body data type must match "Content-Type" header
    })
    return resp
  }

  const handleSubmit = async () => {
    let resp = await submitForm()
    let json = await resp.json();
    if (resp.status === 200) {
      setResult(json.result);
    }
  }

  useEffect(() => {

  }, [formValues, selectValue, result]);

  return (
    <>
      <Head>
        <title>Torvik Gruen - CO2 Rechner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <form className={styles.form}>
            <div className={styles.dropDownWrapper}>
              <label htmlFor="sector">Nutzungsart der Mietfläche:</label>
              <br />
              <select name="sector" onChange={handleFormChange} value={formValues?.sector || "gastro"}>
                <option value="gastro">Gastronomie</option>
                <option value="office" disabled>Büro</option>
                <option value="logistics" disabled>Lager & Logistik</option>
                <option value="pharmacy" disabled>Apotheke</option>
                <option value="office" disabled>Büro</option>
              </select>
            </div>
            <div className={styles.checkBoxWrapper}>
              <div>
                <input
                  type="checkbox"
                  name="wasteReduction"
                  value="wasteReduction"
                  onChange={handleFormChange}
                />
                <label htmlFor="waste-reduction">Vermeidung von Essensabfällen:
                  <input
                    type="text"
                    name="wasteReductionInput"
                    placeholder="X"
                    style={{ border: "none", borderBottom: `${formValues?.wasteReduction && formValues?.wasteReductionInput === "" ? ("2px solid red") : ("2px solid transparent")}` }}
                    value={formValues?.wasteReductionInput}
                    disabled={formValues?.wasteReduction ? (false) : (true)}
                    onChange={handleFormChange}
                  /> kg/Tag
                </label>
              </div>
              <div>
                <input
                  type="checkbox"
                  name="foodSharing"
                  value="foodSharing"
                  onChange={handleFormChange}
                />
                <label htmlFor="foodSharing">Nimmt an Food Sharing teil</label>
              </div>
              <div>
                <input
                  type="checkbox"
                  name="tooGoodToGo"
                  value="tooGoodToGo"
                  onChange={handleFormChange}
                />
                <label htmlFor="tooGoodToGo">Nimmt an "Too good to go" teil</label>
              </div>
            </div>
            <div className={"btn mt-2"} onClick={handleSubmit} action="">CO2 Einsparung kalkulieren</div>
          </form>
          {
            result !== null ? (
              <div className={styles.resultContainer}>
                Die Maßnahmen ergeben eine CO2 Einsparung von: {result} kg pro Jahr
              </div>
            ) : (null)
          }

        </div>

      </main>
    </>
  )
}
