import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import DropDown from '../components/DropDown';
import Hero from '../components/Hero';
import Tabs from '../components/Tabs';
import CheckBox from '../components/CheckBox';

export default function Home() {

  const [selectValue, setSelectValue] = useState("")
  const [formValues, setFormValues] = useState(
    { wasteReduction: false, foodSharing: false, tooGoodToGo: false, wasteReductionInput: '', sector: 'gastro' }
  );
  const [result, setResult] = useState(null)


  const handleFormChange = (name, val) => {
    var value = val
    if (typeof value === 'object') {
      value = value?.target?.value;
    }
    setFormValues({
      ...formValues,
      [name]: value
    })
  }

  const submitForm = async () => {
    let resp = await fetch("api/v1/form", {
      method: 'POST',
      mode: 'cors',
      cache: 'no-cache',
      credentials: 'same-origin',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ "sector": selectValue, ...formValues })
    })
    return resp
  }

  const handleSubmit = async (e) => {
    e.preventDefault();
    let resp = await submitForm()
    let json = await resp.json();
    if (resp.status === 200) {
      setResult(json.result);
    }
  }



  useEffect(() => {
    console.log(formValues)
  }, [formValues, selectValue, result]);

  return (
    <>
      <Head>
        <title>Torvik Gruen - CO2 Rechner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className={styles.main}>
        <div className={styles.container}>
          <form className={styles.form}>
            {/* <DropDown stateControl={[selectValue, setSelectValue]} /> */}
            <Tabs />

            <div className={styles.formContent}>
              <div className={styles.checkBoxWrapper}>
                <div className={styles.checkBoxContainer}>
                  <div className={styles.extendableContainer}>
                    <div style={{ marginTop: "2em", display: "flex", flexDirection: "row", alignItems: "flex-start" }}>
                      <CheckBox
                        name="wasteReduction"
                        value="wasteReduction"
                        state={formValues}
                        stateSetter={handleFormChange}
                      />
                      <div style={{ padding: "0 0 0 1em" }}>
                        <h4>Abfallvermeidung</h4>
                        <p>Wenn der Mieter bereit ist, sein Abfallaufkommen zu reduzieren.</p>
                      </div>
                    </div>
                    <div className={`${styles.extendableContent} ${formValues?.wasteReduction ? (styles.isActive) : ("")}`}>

                      <input
                        type="text"
                        name="wasteReductionInput"
                        placeholder="X"
                        style={{
                          marginRight: "1em",
                        }}
                        value={formValues?.wasteReductionInput}
                        disabled={formValues?.wasteReduction ? (false) : (true)}
                        onChange={(e) => handleFormChange("wasteReductionInput", e)}
                      /> kg/Tag
                    </div>
                  </div>
                </div>
                <div style={{ marginTop: "2em", display: "flex", flexDirection: "row", alignItems: "flex-start" }}>
                  <CheckBox
                    name="foodSharing"
                    value="foodSharing"
                    state={formValues}
                    stateSetter={handleFormChange}
                  />
                  <div style={{ padding: "0 0 0 1em" }}>
                    <h4>Food Sharing</h4>
                    <p>Wenn der Mieter im Programm "Food Sharing" teilnehmen kann.</p>
                  </div>
                </div>
                <div style={{ marginTop: "2em", display: "flex", flexDirection: "row", alignItems: "flex-start" }}>
                  <CheckBox
                    name="tooGoodToGo"
                    value="tooGoodToGo"
                    state={formValues} stateSetter={handleFormChange} />
                  <div style={{ padding: "0 0 0 1em" }}>
                    <h4>Too good to go</h4>
                    <p>Wenn der Mieter im Programm "Too good to go" teilnehmen kann.</p>
                  </div>
                </div>
              </div>
            </div>
            <div style={{ marginTop: "2em" }}>
              <button className={"btn"} onClick={handleSubmit} action="">
                <div className={"btnContent"}>
                  CO2 Einsparung kalkulieren
                </div>
              </button>
            </div>
          </form>
          {
            result !== null ? (
              <div className={styles.resultContainer}>
                Die Maßnahmen ergeben eine CO2 Einsparung von: {result} kg pro Jahr
              </div>
            ) : (null)
          }

        </div>

      </main>
    </>
  )
}
